import "./createTable.css"
function Table(){
    return(
        <table>
            <tr>
            <th>sno</th>
            <th>Name</th>
            <th>phone</th>
            <th>className</th>
            <th>Attendane</th>
            </tr>
            <tr>
                <td>1</td>
                <td>Kowshalya</td>
                <td>13335</td>
                <td>11r</td>
                <td>p</td>
            </tr>
            <tr>
                <td>2</td>
                <td>pavani</td>
                <td>1376357</td>
                <td>11r</td>
                <td>p</td>
            </tr>
            <tr>
                <td>3</td>
                <td>Mounya</td>
                <td>19209357</td>
                <td>11r</td>
                <td>p</td>
            </tr>
            <tr>
                <td>4</td>
                <td>Bhargavi</td>
                <td>99878937</td>
                <td>11r</td>
                <td>p</td>
            </tr>
            <tr>
                <td>5</td>
                <td>Kalyani</td>
                <td>834783</td>
                <td>11r</td>
                <td>p</td>
            </tr>
            <tr>
                <td>6</td>
                <td>E.Bhargavi</td>
                <td>789879</td>
                <td>11r</td>
                <td>p</td>
            </tr>
            <tr>
                <td>7</td>
                <td>Swomya</td>
                <td>75875</td>
                <td>11r</td>
                <td>p</td>
            </tr>
            <tr>
                <td>8</td>
                <td>Sravani</td>
                <td>7678658375</td>
                <td>11r</td>
                <td>p</td>
            </tr>
            <tr>
                <td>9</td>
                <td>Udaya</td>
                <td>8947598</td>
                <td>11r</td>
                <td>p</td>
            </tr>
            <tr>
                <td>10</td>
                <td>Swathi</td>
                <td>898459</td>
                <td>11r</td>
                <td>p</td>
            </tr>
        </table>
    )
}
export default Table